### ISSUE TITLE
Slow startup time

### ISSUE THREAD

**Issue by devicenull** [RIPE-NCC/rpki-validator-3#61] opened 2019-01-10 17:10 UTC
I just upgraded to 3.0-333, and the validator is now taking quite some time to startup.

strace reveals it's trying to read the database:

<pre>
[pid 13853] pread64(14, "\0\0\2\265\343B4\5\1\10\267\36\200\22\20'\22\10\267\36\200\22\20\310\222\10\267\36\200\22\21i"..., 768, 6532230631) = 768
[pid 13853] pread64(14, "\0\0\2\211\221\"4\5\1\10\267\36\200\22\24\221\22\10\267\36\200\22\0252\222\10\267\36\200\22\25\323"..., 768, 6532235195) = 768
[pid 13853] pread64(14, "\0\0\2\265\277\2224\5\1\10\267\36\200\22\30\373\22\10\267\36\200\22\31\234R\10\267\36\200\22\32="..., 768, 6532239671) = 768
[pid 13853] pread64(14, "\0\0\2\265\255\2574\5\1\10\267\36\200\22\35o\322\10\267\36\200\22\36\21\22\10\267\36\200\22\36\262"..., 768, 6532244234) = 768
[pid 13853] pread64(14, "\0\0\2\265Zx4\5\1\10\267\36\200\22!\344\222\10\267\36\200\22\"\205\322\10\267\36\200\22#'"..., 768, 6532248797) = 768
[pid 13853] pread64(14, "\0\0\2\265H\0244\5\1\10\267\36\200\22&Y\222\10\267\36\200\22&\372\322\10\267\36\200\22'\234"..., 768, 6532253361) = 768
[pid 13853] pread64(14, "\0\0\2\265v!4\5\1\10\267\36\200\22*\316S\10\267\36\200\22/9S\10\267\36\200\0223\256"..., 768, 6532257924) = 768

java    13820 rpki   14uW  REG              253,1 53416288256   387377 /var/lib/rpki-validator-3/db/rpki-validator.h2.mv.db

# du -shx /var/lib/rpki-validator-3/db/rpki-validator.h2.mv.db
50G     /var/lib/rpki-validator-3/db/rpki-validator.h2.mv.db
</pre>

Any idea why the database has grown to 50GB here?  All the docs I can find seem to indicate this should be around 10GB.  Is there any option to force garbage collection?

**Comment by lolepezy** [comment] 2019-01-11 16:23
Hi, 

Is there any chance you could compress and publish it so we could download and investigate if there are some bloated tables? It is indeed weird, normally the validator should delete objects older than 7 days from the database. So even for the most frequent updates, the size of the storage cannot grow indefinitely. But it looks like it's not the case for you.

As a work around for now I would suggest to reduce the 'rpki.validator.rpki.object.cleanup.grace.duration' setting from 7 days to, say, one day (i.e. from P7D to P1D) and see if it gets smaller.

**Comment by devicenull** [comment] 2019-01-14 15:53
Unfortunately, I had deleted this file in order to restore service (this runs on a VM with limited disk space).  I'll save a copy if I see this grow to 50gb again.

**Comment by d4nys3k** [comment] 2019-01-22 15:23
Hello,
I'm observing quite similar behavior starting with upgrade to version 3.0-340 (from 3.0-313). Database seems to be growing more quickly compared to previous version - see graph below. Also increased I/O is observed after some period, mostly read operations. After deleting rpki-validator.h2.mv.db, normal operation is restored for some time. Today we moved to 3.0-357 and we'll see if issue is still there, also we applied workaround suggested by [lolepezy](https://github.com/RIPE-NCC/rpki-validator-3/issues/61#issuecomment-453572566), just to be sure.

![df_abs-month](https://user-images.githubusercontent.com/16295884/51544324-f43ee600-1e5f-11e9-957c-2854a7cdea33.png)
![io-month](https://user-images.githubusercontent.com/16295884/51544737-d6be4c00-1e60-11e9-9fba-87a762054cc2.png)

**Comment by lolepezy** [comment] 2019-01-23 13:23
Hi,

We are trying to reproduce and investigating the issue. It seems to be related to how H2 (the embedded database we use is handling the storage). We hope to have a fix in the next build.

**Comment by devicenull** [comment] 2019-01-29 19:53
I just upgraded to -355, but the database I had was only 3.7 GB, so I'm not sure I can confirm if it's fixed or not.  I have not (yet) seen the database balloon in size

**Comment by d4nys3k** [comment] 2019-03-22 07:45
Shortly after upgrade to 3.0-397 db growed up unexpectly again. Before that, we were running 3.0-386 without any problems. As quick workaround, h2 databases (mv,trace) was deleted, we'll see what happens after this.
![df_abs-week](https://user-images.githubusercontent.com/16295884/54807461-9a9b4200-4c7d-11e9-9373-31aed297027f.png)

**Comment by lolepezy** [comment] 2019-07-04 10:14
We believe the issue should be resolved in the 3.1 version.

**Closed by lolepezy** 2019-07-04 10:14 UTC
